//number all int folat double and long and charcterand all integer
//string chsr  array
//boolean true or false
//symbol we are
console.log(323);
console.log("string");
console.log(0b11);
let boy =true;
console.log(boy);
let val=null;
let undefined;
console.log(undefined);
let id =Symbol("id");
console.log("id");

let big =383883388838383833838833;
console.log(big);
let teju={
    color:"white",
    height:"FIFTEEN ",
    hair: "black",
    company : "Amazon",
    house: "black",

};
console.log(teju.color);

const x=0;
let num;
if(num>0){
    console.log("It is positive");

}
else if(num<0){
    console.log("It is negative ");   
}
else{
    console.log("It is zero");
}
function add(number2,number4){
    return number2*number4;

    
}
console.log(add(6,9));